
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.2 EDK_O.61xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_GENERIC_IIC_BUS_DEVICE_ID,
		XPAR_GENERIC_IIC_BUS_BASEADDR,
		XPAR_GENERIC_IIC_BUS_TEN_BIT_ADR,
		XPAR_GENERIC_IIC_BUS_GPO_WIDTH
	}
};


